# WARNING
# This file is autogenerated and should not be modified directly.
# For more details, see https://github.com/acceleratedscience/openad-website/tree/main/generator
# Template file: https://github.com/acceleratedscience/openad-website/tree/main/generator/_source/concepts.py

"""
Snippets used for the help output:
- Descriptions of OpenAD and some of its key concepts
- The introductionary text generated for the `intro` command
"""

# Concept description
# These are auto-generated from https://github.com/acceleratedscience/openad-website/tree/main/generator/_source
description = INSERT_HERE
about_mws = INSERT_HERE
about_workspace = INSERT_HERE
about_plugin = INSERT_HERE
about_run = INSERT_HERE
about_context = """Setting context is deprecated, install RXN/DS plugins instead."""


openad_intro: str = f"""<h1>Introduction to OpenAD</h1>

{description}

<link>accelerate.science/projects/openad</link>



<h2>Molecule Working Set</h2>
{about_mws}

<soft>To see how to work with your molecule working set, run <cmd>? mws</cmd></soft>



<h2>Workspaces</h2>
{about_workspace}

<soft>To see how to work with workspaces, run <cmd>? workspace</cmd></soft>



<h2>Plugins</h2>
{about_plugin}

<soft>To see how to work with plugins, run <cmd>? toolkit</cmd></soft>



<h2>Runs</h2>
{about_run}

<soft>To see how to work with runs, run <cmd>? run</cmd></soft>"""
