from .shared import (
    read_source_file,
    read_docs_file,
    update_autogenerated_section,
    write_output_file,
)
from openad.helpers.output import output_text


# Update the docs/plugins.md file with the about_plugins description
def update_plugins_md(filename="plugins.md"):
    output_text(
        f"<h1>Updating <yellow>{filename}</yellow> with about_plugins description</h1>",
        pad_top=2,
    )

    # Read base file content
    readme_plugin_md = read_docs_file(filename)
    if not readme_plugin_md:
        return

    # Read source file content
    about_plugins_txt = read_source_file("about_plugins.txt")
    if not about_plugins_txt:
        return

    # Insert description
    readme_plugin_md = update_autogenerated_section(
        readme_plugin_md, "plugins", about_plugins_txt
    )
    if not readme_plugin_md:
        return

    # Write to output file
    write_output_file("docs/" + filename, readme_plugin_md)
