from .shared import (
    fetch_gh_file,
    read_source_file,
    update_autogenerated_section,
    write_output_file,
)
from openad.helpers.output import output_text


# Update the main README.md for the openad-toolkit repo with OpenAD description
def update_gh_readme(filename="README.md"):
    output_text(
        f"<h1>Updating <yellow>{filename}</yellow> with OpenAD description</h1>",
        pad_top=2,
    )

    # Read base file content
    readme_md = fetch_gh_file("README.md")
    if not readme_md:
        return

    # Read source file content
    description_txt = read_source_file("description.txt")
    if not description_txt:
        return

    # Insert description
    readme_md = update_autogenerated_section(readme_md, "description", description_txt)
    if not readme_md:
        return

    # Write to output file
    write_output_file("openad-toolkit/" + filename, readme_md)
